<?php

declare(strict_types=1);

namespace Idiot\Zabbix\Api\Requests\Enums;

/**
 * Return only alerts generated by events related to objects of the given type. Possible values depend on eventsource: if eventsource = 0 (trigger): 0 - trigger; if eventsource = 1 (discovery rule): 1 - discovered host, 2 - discovered service; if eventsource = 2 (active agent autoregistration): 3 - auto-registered host; if eventsource = 3 (internal event): 0 - trigger, 4 - item, 5 - LLD rule; if eventsource = 4 (service status update): 6 - service. Default: 0 - trigger.
 */
enum AlertEventobject: int
{
    case Trigger = 0;
    case DiscoveredHost = 1;
    case V2 = 2;
    case AutoRegisteredHost = 3;
    case V4 = 4;
    case V5 = 5;
    case Service = 6;
}
