<?php declare(strict_types=1);

namespace Idiot\Zabbix\Requests\Schemas;

use Idiot\Zabbix\Requests\RequestSchema;

final class TokenGenerateSchema extends RequestSchema
{
    /**
     * Draft 2020-12 schema for token.generate, compiled from the source JSON at
     * build time. No JSON is read at runtime.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            '$schema' => 'https://json-schema.org/draft/2020-12/schema',
            '$id' => 'https://zabbix.com/7.0/api/token/token.generate',
            'title' => 'token.generate',
            'description' => 'Generate tokens. A token can be generated by this method only if it has been created (token.create) first.',
            '$comment' => 'Source: https://www.zabbix.com/documentation/7.0/en/manual/api/reference/token/generate',
            'type' => 'array',
            'items' => [
                'type' => 'string',
            ],
            'minItems' => 1,
        ];
    }
}
