<?php declare(strict_types=1);

namespace IntelliTrend\Zabbix\Requests\Schemas;

use IntelliTrend\Zabbix\Requests\RequestSchema;

final class TriggerUpdateSchema extends RequestSchema
{
    /**
     * Draft 2020-12 schema for trigger.update, compiled from the source JSON at
     * build time. No JSON is read at runtime.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            '$schema' => 'https://json-schema.org/draft/2020-12/schema',
            '$id' => 'https://zabbix.com/7.0/api/trigger/trigger.update',
            'title' => 'trigger.update',
            'description' => 'Update existing triggers.',
            '$comment' => 'Source: https://www.zabbix.com/documentation/7.0/en/manual/api/reference/trigger/update',
            'type' => 'object',
            'properties' => [
                'triggerid' => [
                    'type' => 'string',
                    'description' => 'ID of the trigger to update.',
                ],
                'description' => [
                    'type' => 'string',
                    'description' => 'Name of the trigger.',
                ],
                'expression' => [
                    'type' => 'string',
                    'description' => 'Trigger expression.

Items with value_type set to 5 (binary) cannot be used in trigger expressions.',
                ],
                'event_name' => [
                    'type' => 'string',
                    'description' => 'Event name generated by the trigger.',
                ],
                'opdata' => [
                    'type' => 'string',
                    'description' => 'Operational data.',
                ],
                'comments' => [
                    'type' => 'string',
                    'description' => 'Additional description of the trigger.',
                ],
                'priority' => [
                    'type' => 'integer',
                    'description' => 'Severity of the trigger.

Possible values:
0 - (default) not classified;
1 - information;
2 - warning;
3 - average;
4 - high;
5 - disaster.',
                    'enum' => [
                        0,
                        1,
                        2,
                        3,
                        4,
                        5,
                    ],
                ],
                'status' => [
                    'type' => 'integer',
                    'description' => 'Whether the trigger is enabled or disabled.

Possible values:
0 - (default) enabled;
1 - disabled.',
                    'enum' => [
                        0,
                        1,
                    ],
                ],
                'type' => [
                    'type' => 'integer',
                    'description' => 'Whether the trigger can generate multiple problem events.

Possible values:
0 - (default) do not generate multiple events;
1 - generate multiple events.',
                    'enum' => [
                        0,
                        1,
                    ],
                ],
                'url' => [
                    'type' => 'string',
                    'description' => 'URL associated with the trigger.',
                ],
                'url_name' => [
                    'type' => 'string',
                    'description' => 'Label for the URL associated with the trigger.',
                ],
                'recovery_mode' => [
                    'type' => 'integer',
                    'description' => 'OK event generation mode.

Possible values:
0 - (default) Expression;
1 - Recovery expression;
2 - None.',
                    'enum' => [
                        0,
                        1,
                        2,
                    ],
                ],
                'recovery_expression' => [
                    'type' => 'string',
                    'description' => 'Trigger recovery expression.

Items with value_type set to 5 (binary) cannot be used in trigger recovery expressions.',
                ],
                'correlation_mode' => [
                    'type' => 'integer',
                    'description' => 'OK event closes.

Possible values:
0 - (default) All problems;
1 - All problems if tag values match.',
                    'enum' => [
                        0,
                        1,
                    ],
                ],
                'correlation_tag' => [
                    'type' => 'string',
                    'description' => 'Tag for matching.',
                ],
                'manual_close' => [
                    'type' => 'integer',
                    'description' => 'Allow manual close.

Possible values:
0 - (default) No;
1 - Yes.',
                    'enum' => [
                        0,
                        1,
                    ],
                ],
                'uuid' => [
                    'type' => 'string',
                    'description' => 'Universal unique identifier, used for linking imported triggers to already existing ones. Auto-generated, if not given.

Supported if the trigger belongs to a template.',
                ],
                'dependencies' => [
                    'type' => 'array',
                    'items' => [
                        'type' => 'object',
                        'description' => 'Trigger that this trigger is dependent on. The triggers must have only the triggerid property defined.',
                        'properties' => [
                            'triggerid' => [
                                'type' => 'string',
                                'description' => 'ID of the trigger that this trigger depends on.',
                            ],
                        ],
                        'required' => [
                            'triggerid',
                        ],
                        'additionalProperties' => false,
                    ],
                    'description' => 'Triggers that the trigger is dependent on.

The triggers must have only the triggerid property defined.',
                ],
                'tags' => [
                    'type' => 'array',
                    'items' => [
                        'type' => 'object',
                        'properties' => [
                            'tag' => [
                                'type' => 'string',
                                'description' => 'Trigger tag name.',
                            ],
                            'value' => [
                                'type' => 'string',
                                'description' => 'Trigger tag value.',
                            ],
                        ],
                        'required' => [
                            'tag',
                        ],
                        'additionalProperties' => false,
                    ],
                    'description' => 'Trigger tags.',
                ],
            ],
            'required' => [
                'triggerid',
            ],
            'additionalProperties' => false,
        ];
    }
}
