<?php

declare(strict_types=1);

namespace Idiot\Zabbix\Requests;

/**
 * Maps a Zabbix method name to its generated request class.
 */
final class StaticRequestRegistry implements ZabbixRequestRegistry
{
    /** @var array<string, class-string<ZabbixRequest>> */
    private const REQUEST_CLASSES = [
        'action.create' => ActionCreateRequest::class,
        'action.delete' => ActionDeleteRequest::class,
        'action.get' => ActionGetRequest::class,
        'action.update' => ActionUpdateRequest::class,
        'alert.get' => AlertGetRequest::class,
        'apiinfo.version' => ApiinfoVersionRequest::class,
        'auditlog.get' => AuditlogGetRequest::class,
        'authentication.get' => AuthenticationGetRequest::class,
        'authentication.update' => AuthenticationUpdateRequest::class,
        'autoregistration.get' => AutoregistrationGetRequest::class,
        'autoregistration.update' => AutoregistrationUpdateRequest::class,
        'connector.create' => ConnectorCreateRequest::class,
        'connector.delete' => ConnectorDeleteRequest::class,
        'connector.get' => ConnectorGetRequest::class,
        'connector.update' => ConnectorUpdateRequest::class,
        'correlation.create' => CorrelationCreateRequest::class,
        'correlation.delete' => CorrelationDeleteRequest::class,
        'correlation.get' => CorrelationGetRequest::class,
        'correlation.update' => CorrelationUpdateRequest::class,
        'dashboard.create' => DashboardCreateRequest::class,
        'dashboard.delete' => DashboardDeleteRequest::class,
        'dashboard.get' => DashboardGetRequest::class,
        'dashboard.update' => DashboardUpdateRequest::class,
        'dcheck.get' => DcheckGetRequest::class,
        'dhost.get' => DhostGetRequest::class,
        'discoveryrule.copy' => DiscoveryruleCopyRequest::class,
        'discoveryrule.create' => DiscoveryruleCreateRequest::class,
        'discoveryrule.delete' => DiscoveryruleDeleteRequest::class,
        'discoveryrule.get' => DiscoveryruleGetRequest::class,
        'discoveryrule.update' => DiscoveryruleUpdateRequest::class,
        'drule.create' => DruleCreateRequest::class,
        'drule.delete' => DruleDeleteRequest::class,
        'drule.get' => DruleGetRequest::class,
        'drule.update' => DruleUpdateRequest::class,
        'dservice.get' => DserviceGetRequest::class,
        'event.acknowledge' => EventAcknowledgeRequest::class,
        'event.get' => EventGetRequest::class,
        'graph.create' => GraphCreateRequest::class,
        'graph.delete' => GraphDeleteRequest::class,
        'graph.get' => GraphGetRequest::class,
        'graph.update' => GraphUpdateRequest::class,
        'graphitem.get' => GraphitemGetRequest::class,
        'graphprototype.create' => GraphprototypeCreateRequest::class,
        'graphprototype.delete' => GraphprototypeDeleteRequest::class,
        'graphprototype.get' => GraphprototypeGetRequest::class,
        'graphprototype.update' => GraphprototypeUpdateRequest::class,
        'hanode.get' => HanodeGetRequest::class,
        'history.clear' => HistoryClearRequest::class,
        'history.get' => HistoryGetRequest::class,
        'history.push' => HistoryPushRequest::class,
        'host.create' => HostCreateRequest::class,
        'host.delete' => HostDeleteRequest::class,
        'host.get' => HostGetRequest::class,
        'host.massadd' => HostMassaddRequest::class,
        'host.massremove' => HostMassremoveRequest::class,
        'host.massupdate' => HostMassupdateRequest::class,
        'host.update' => HostUpdateRequest::class,
        'hostgroup.create' => HostgroupCreateRequest::class,
        'hostgroup.delete' => HostgroupDeleteRequest::class,
        'hostgroup.get' => HostgroupGetRequest::class,
        'hostgroup.massadd' => HostgroupMassaddRequest::class,
        'hostgroup.massremove' => HostgroupMassremoveRequest::class,
        'hostgroup.massupdate' => HostgroupMassupdateRequest::class,
        'hostgroup.propagate' => HostgroupPropagateRequest::class,
        'hostgroup.update' => HostgroupUpdateRequest::class,
        'hostinterface.create' => HostinterfaceCreateRequest::class,
        'hostinterface.delete' => HostinterfaceDeleteRequest::class,
        'hostinterface.get' => HostinterfaceGetRequest::class,
        'hostinterface.massadd' => HostinterfaceMassaddRequest::class,
        'hostinterface.massremove' => HostinterfaceMassremoveRequest::class,
        'hostinterface.replacehostinterfaces' => HostinterfaceReplacehostinterfacesRequest::class,
        'hostinterface.update' => HostinterfaceUpdateRequest::class,
        'hostprototype.create' => HostprototypeCreateRequest::class,
        'hostprototype.delete' => HostprototypeDeleteRequest::class,
        'hostprototype.get' => HostprototypeGetRequest::class,
        'hostprototype.update' => HostprototypeUpdateRequest::class,
        'housekeeping.get' => HousekeepingGetRequest::class,
        'housekeeping.update' => HousekeepingUpdateRequest::class,
        'httptest.create' => HttptestCreateRequest::class,
        'httptest.delete' => HttptestDeleteRequest::class,
        'httptest.get' => HttptestGetRequest::class,
        'httptest.update' => HttptestUpdateRequest::class,
        'iconmap.create' => IconmapCreateRequest::class,
        'iconmap.delete' => IconmapDeleteRequest::class,
        'iconmap.get' => IconmapGetRequest::class,
        'iconmap.update' => IconmapUpdateRequest::class,
        'image.create' => ImageCreateRequest::class,
        'image.delete' => ImageDeleteRequest::class,
        'image.get' => ImageGetRequest::class,
        'image.update' => ImageUpdateRequest::class,
        'item.create' => ItemCreateRequest::class,
        'item.delete' => ItemDeleteRequest::class,
        'item.get' => ItemGetRequest::class,
        'item.update' => ItemUpdateRequest::class,
        'itemprototype.create' => ItemprototypeCreateRequest::class,
        'itemprototype.delete' => ItemprototypeDeleteRequest::class,
        'itemprototype.get' => ItemprototypeGetRequest::class,
        'itemprototype.update' => ItemprototypeUpdateRequest::class,
        'maintenance.create' => MaintenanceCreateRequest::class,
        'maintenance.delete' => MaintenanceDeleteRequest::class,
        'maintenance.get' => MaintenanceGetRequest::class,
        'maintenance.update' => MaintenanceUpdateRequest::class,
        'map.create' => MapCreateRequest::class,
        'map.delete' => MapDeleteRequest::class,
        'map.get' => MapGetRequest::class,
        'map.update' => MapUpdateRequest::class,
        'mediatype.create' => MediatypeCreateRequest::class,
        'mediatype.delete' => MediatypeDeleteRequest::class,
        'mediatype.get' => MediatypeGetRequest::class,
        'mediatype.update' => MediatypeUpdateRequest::class,
        'mfa.create' => MfaCreateRequest::class,
        'mfa.delete' => MfaDeleteRequest::class,
        'mfa.get' => MfaGetRequest::class,
        'mfa.update' => MfaUpdateRequest::class,
        'module.create' => ModuleCreateRequest::class,
        'module.delete' => ModuleDeleteRequest::class,
        'module.get' => ModuleGetRequest::class,
        'module.update' => ModuleUpdateRequest::class,
        'problem.get' => ProblemGetRequest::class,
        'proxy.create' => ProxyCreateRequest::class,
        'proxy.delete' => ProxyDeleteRequest::class,
        'proxy.get' => ProxyGetRequest::class,
        'proxy.update' => ProxyUpdateRequest::class,
        'proxygroup.create' => ProxygroupCreateRequest::class,
        'proxygroup.delete' => ProxygroupDeleteRequest::class,
        'proxygroup.get' => ProxygroupGetRequest::class,
        'proxygroup.update' => ProxygroupUpdateRequest::class,
        'regexp.create' => RegexpCreateRequest::class,
        'regexp.delete' => RegexpDeleteRequest::class,
        'regexp.get' => RegexpGetRequest::class,
        'regexp.update' => RegexpUpdateRequest::class,
        'report.create' => ReportCreateRequest::class,
        'report.delete' => ReportDeleteRequest::class,
        'report.get' => ReportGetRequest::class,
        'report.update' => ReportUpdateRequest::class,
        'role.create' => RoleCreateRequest::class,
        'role.delete' => RoleDeleteRequest::class,
        'role.get' => RoleGetRequest::class,
        'role.update' => RoleUpdateRequest::class,
        'script.create' => ScriptCreateRequest::class,
        'script.delete' => ScriptDeleteRequest::class,
        'script.execute' => ScriptExecuteRequest::class,
        'script.get' => ScriptGetRequest::class,
        'script.getscriptsbyevents' => ScriptGetscriptsbyeventsRequest::class,
        'script.getscriptsbyhosts' => ScriptGetscriptsbyhostsRequest::class,
        'script.update' => ScriptUpdateRequest::class,
        'service.create' => ServiceCreateRequest::class,
        'service.delete' => ServiceDeleteRequest::class,
        'service.get' => ServiceGetRequest::class,
        'service.update' => ServiceUpdateRequest::class,
        'settings.get' => SettingsGetRequest::class,
        'settings.update' => SettingsUpdateRequest::class,
        'sla.create' => SlaCreateRequest::class,
        'sla.delete' => SlaDeleteRequest::class,
        'sla.get' => SlaGetRequest::class,
        'sla.getsli' => SlaGetsliRequest::class,
        'sla.update' => SlaUpdateRequest::class,
        'task.create' => TaskCreateRequest::class,
        'task.get' => TaskGetRequest::class,
        'template.create' => TemplateCreateRequest::class,
        'template.delete' => TemplateDeleteRequest::class,
        'template.get' => TemplateGetRequest::class,
        'template.massadd' => TemplateMassaddRequest::class,
        'template.massremove' => TemplateMassremoveRequest::class,
        'template.massupdate' => TemplateMassupdateRequest::class,
        'template.update' => TemplateUpdateRequest::class,
        'templatedashboard.create' => TemplatedashboardCreateRequest::class,
        'templatedashboard.delete' => TemplatedashboardDeleteRequest::class,
        'templatedashboard.get' => TemplatedashboardGetRequest::class,
        'templatedashboard.update' => TemplatedashboardUpdateRequest::class,
        'templategroup.create' => TemplategroupCreateRequest::class,
        'templategroup.delete' => TemplategroupDeleteRequest::class,
        'templategroup.get' => TemplategroupGetRequest::class,
        'templategroup.massadd' => TemplategroupMassaddRequest::class,
        'templategroup.massremove' => TemplategroupMassremoveRequest::class,
        'templategroup.massupdate' => TemplategroupMassupdateRequest::class,
        'templategroup.propagate' => TemplategroupPropagateRequest::class,
        'templategroup.update' => TemplategroupUpdateRequest::class,
        'token.create' => TokenCreateRequest::class,
        'token.delete' => TokenDeleteRequest::class,
        'token.generate' => TokenGenerateRequest::class,
        'token.get' => TokenGetRequest::class,
        'token.update' => TokenUpdateRequest::class,
        'trend.get' => TrendGetRequest::class,
        'trigger.create' => TriggerCreateRequest::class,
        'trigger.delete' => TriggerDeleteRequest::class,
        'trigger.get' => TriggerGetRequest::class,
        'trigger.update' => TriggerUpdateRequest::class,
        'triggerprototype.create' => TriggerprototypeCreateRequest::class,
        'triggerprototype.delete' => TriggerprototypeDeleteRequest::class,
        'triggerprototype.get' => TriggerprototypeGetRequest::class,
        'triggerprototype.update' => TriggerprototypeUpdateRequest::class,
        'user.checkAuthentication' => UserCheckAuthenticationRequest::class,
        'user.create' => UserCreateRequest::class,
        'user.delete' => UserDeleteRequest::class,
        'user.get' => UserGetRequest::class,
        'user.login' => UserLoginRequest::class,
        'user.logout' => UserLogoutRequest::class,
        'user.provision' => UserProvisionRequest::class,
        'user.resettotp' => UserResettotpRequest::class,
        'user.unblock' => UserUnblockRequest::class,
        'user.update' => UserUpdateRequest::class,
        'userdirectory.create' => UserdirectoryCreateRequest::class,
        'userdirectory.delete' => UserdirectoryDeleteRequest::class,
        'userdirectory.get' => UserdirectoryGetRequest::class,
        'userdirectory.test' => UserdirectoryTestRequest::class,
        'userdirectory.update' => UserdirectoryUpdateRequest::class,
        'usergroup.create' => UsergroupCreateRequest::class,
        'usergroup.delete' => UsergroupDeleteRequest::class,
        'usergroup.get' => UsergroupGetRequest::class,
        'usergroup.update' => UsergroupUpdateRequest::class,
        'usermacro.create' => UsermacroCreateRequest::class,
        'usermacro.createglobal' => UsermacroCreateglobalRequest::class,
        'usermacro.delete' => UsermacroDeleteRequest::class,
        'usermacro.deleteglobal' => UsermacroDeleteglobalRequest::class,
        'usermacro.get' => UsermacroGetRequest::class,
        'usermacro.update' => UsermacroUpdateRequest::class,
        'usermacro.updateglobal' => UsermacroUpdateglobalRequest::class,
        'valuemap.create' => ValuemapCreateRequest::class,
        'valuemap.delete' => ValuemapDeleteRequest::class,
        'valuemap.get' => ValuemapGetRequest::class,
        'valuemap.update' => ValuemapUpdateRequest::class,
    ];

    public function methods(): array
    {
        return array_keys(self::REQUEST_CLASSES);
    }

    public function requestClassFor(string $method): string
    {
        return self::REQUEST_CLASSES[$method] ?? throw UnknownZabbixMethod::method($method);
    }

    public function requestFor(string $method, array $params = []): ZabbixRequest
    {
        $requestClass = $this->requestClassFor($method);

        if (is_a($requestClass, AbstractZabbixRequest::class, true)) {
            return $requestClass::fromParams($params);
        }

        throw new \LogicException(sprintf(
            'Registered request class %s cannot be constructed from params.',
            $requestClass,
        ));
    }
}
