<?php declare(strict_types=1);

namespace Idiot\Zabbix\Requests\Enums;

/**
 * Return only alerts generated by events of the given type. Possible values: 0 - event created by a trigger; 1 - event created by a discovery rule; 2 - event created by active agent autoregistration; 3 - internal event; 4 - event created on service status update. Default: 0 - trigger events.
 */
enum AlertEventsource: int
{
    case TriggerEvents = 0;
    case EventCreatedByADiscovery = 1;
    case EventCreatedByActiveAgent = 2;
    case InternalEvent = 3;
    case EventCreatedOnServiceStatus = 4;
}
